const businesses = [
  {
    name: "Business 1",
    imageUrl: "https://example.com/business1.jpg",
    text: "",
    price: 50,
    gainPerHour: 5,
    purchaseDate: null,
    lastCollectionDate: null,
    earnings: 0,
    totalEarning: 0,
  },
  {
    name: "Business 2",
    imageUrl: "https://example.com/business2.jpg",
    text: "",
    price: 100000,
    gainPerHour: 5000,
    purchaseDate: null,
    lastCollectionDate: null,
    earnings: 0,
    totalEarning: 0,
  },
  {
    name: "Business 3",
    imageUrl: "https://example.com/business2.jpg",
    text: "",
    price: 100000,
    gainPerHour: 5000000,
    purchaseDate: null,
    lastCollectionDate: null,
    earnings: 0,
    totalEarning: 0,
  },
];
