const businesses = [
  {
    id: 1,
    name: "Race Horse",
    imageUrl: "https://minio.yalispor.com.tr/yalispor/blog/baslik_62398fa37c1c5.jpg",
    text: "Race Horse - 25000₺",
    price: 25000,
    gainPerHour: 100,
    purchaseDate: null,
    lastCollectionDate: null,
    earnings: 0,
    totalEarning: 0,
  },
  {
    id: 2,
    name: "Los Pollos Hermanos",
    imageUrl: "https://wallpapercave.com/wp/wp8477495.jpg",
    text: "Fast Food Restaurant - 50000₺",
    price: 50000,
    gainPerHour: 200,
    purchaseDate: null,
    lastCollectionDate: null,
    earnings: 0,
    totalEarning: 0,
  },
  {
    id: 3,
    name: "Car Gallery",
    imageUrl: "https://img.321ignition.io/321ignition-v4-prod-images/public/5fd8fe137b4cbc001cf98892/common/share_CarmelAutoGallery.jpg",
    text: "Luxury Car Gallery - 100000₺",
    price: 100000,
    gainPerHour: 600,
    purchaseDate: null,
    lastCollectionDate: null,
    earnings: 0,
    totalEarning: 0,
  },
  {
    id: 4,
    name: "Hotel",
    imageUrl: "https://cdn3.enuygun.com/media/lib//uploads/image/hilton-istanbul-bosphorus-istanbul-genel-37295684.jpg",
    text: "Hotel - 200000₺",
    price: 200000,
    gainPerHour: 1200,
    purchaseDate: null,
    lastCollectionDate: null,
    earnings: 0,
    totalEarning: 0,
  },
];
